### ISSUE TITLE
[Feature request] Add option to not check for dockcheck updates

### ISSUE THREAD

**Issue by dst78** [mag37/dockcheck#113]
For me, dockcheck is feature complete, it would be neat to have an option to have it not check for updates of itself. 

Thanks!

**Comment by mag37** [comment]
Glad you like it and think it's done :smiley:   

Some updates are not feature updates but because of breakage/changes/bugreports.   
If running with `-y/-a` or `-n` the update interaction will be skipped. I'll consider adding a flag for not updating too, but will still print the update message if so.

**Comment by mag37** [comment]
No rush from my end, focus on the family/house and report back later. 

Another temporary solution is just to comment out the version-check logic in your local script, line 162:
```
# Version check & initiate self update
# if [[ "$VERSION" != "$LatestRelease" ]] ; then
#  printf "New version available! %b%s%b ⇒ %b%s%b \n Change Notes: %s \n" "$c_yellow" "$VERSION" "$c_reset"  $c_green" "$LatestRelease" "$c_reset" "$LatestChanges"
#  if [[ -z "$AutoUp" ]] ; then
#    read -r -p "Would you like to update? y/[n]: " SelfUpdate
#    [[ "$SelfUpdate" =~ [yY] ]] && self_update
#  fi
#fi
```

**Comment by mag37** [comment]
The version aint a typo, just forgot to finalize the release+tag! Will sort it tomorrow.

`AutoUp` will update images but not dockcheck itself, though it will skip the interaction and only print that there's an update available (else it would wait for interaction y/n before continuing). 

If it ain't doing what you'd like - I'll look into working your  FR in, just might hold it until something else needs fixing before merging to main. But it's an easy implementation, already got a mockup in my test env.

Until then, what you could do is the workaround I posted above, just comment out that section.

**Comment by mag37** [comment]
Or sorry, I misunderstood then! 

So you're still getting an email with the script-update - that's very odd! Might be due to your cron setup yes.. let me know if it continues, as I dont understand how it should be possible!
This is the code:
```sh
if [[ -n ${GotUpdates[*]} ]] ; then
   printf "\n%bContainers with updates available:%b\n" "$c_yellow" "$c_reset"
   [[ -z "$AutoUp" ]] && options || printf "%s\n" "${GotUpdates[@]}"
   [[ -n "$Notify" ]] && { [[ $(type -t send_notification) == function ]] && send_notification "${GotUpdates[@]}" || printf "Could not source notification function.\n" ; }
fi
```

So it'll check if the `$Notify` variable is set, if so it'll source the notification function and send the array `${GotUpdates[@]}` - no other data is passed to the notification function.

**Comment by mag37** [comment]
Great, sorry completely forgot about following up on this.
