### ISSUE TITLE
Keep getting this when i try to update some containers 

### ISSUE THREAD

**Issue by chiragvshroff** [mag37/dockcheck#13]
![image](https://user-images.githubusercontent.com/49506078/218036519-9bb54414-a0aa-4135-88d9-6da098cfa09c.png)

**Comment by mag37** [comment]
Would you mind pasting the output of   
`docker inspect Photoprism --format '{{ index .Config.Labels "com.docker.compose.project.config_files" }}'`   
and   
`docker inspect Photoprism --format '{{ index .Config.Labels "com.docker.compose.service" }}'`   

You can clean your directories/usernames to something random to not reveal unnecessary info. Just interested in the format.

**Comment by mag37** [comment]
Are this specific container started with `docker run` ? 
As this script will only properly update and restart containers started with `docker compose`. 
From trying to troubleshoot it seems like the paths extracted for the compose-file is empty - good find thou, I'll include some kind of check for this in the future.

**Comment by msrheidema** [comment]
run this:
```docker inspect Photoprism --format='{{range $k, $v := .Config.Labels}}{{println $k}}{{println $v}}{{end}}'```

It will show all the info including how the docker is running and if it's a docker compose

**Comment by mag37** [comment]
I've made a fix to allow for skipping containers which are started with `docker run` (default setting). 
Or if ran with the `-r` flag you'll allow for those containers to get new images downloaded too - though due to `docker run` the actual container wont get auto updated.

Check testing-branch: [dockcheck.sh](https://github.com/mag37/dockcheck/blob/testing/dockcheck.sh)
I'll do some more testing before I merge with main - this would additionally render the `dockcheck_docker-run_ver.sh` obsolete.

**Comment by chiragvshroff** [comment]
> I've made a fix to allow for skipping containers which are started with `docker run` (default setting). 
> 
> Or if ran with the `-r` flag you'll allow for those containers to get new images downloaded too - though due to `docker run` the actual container wont get auto updated.
> 
> 
> 
> Check testing-branch: [dockcheck.sh](https://github.com/mag37/dockcheck/blob/testing/dockcheck.sh)
> 
> I'll do some more testing before I merge with main - this would additionally render the `dockcheck_docker-run_ver.sh` obsolete.

Yeah this is happening only with `docker run` containers works fine with containers deployed using docker compose
