### ISSUE TITLE
Only update container if the new container is X days old

### ISSUE THREAD

**Issue by doguitar** [mag37/dockcheck#45]
I've been looking for something that would let me auto update to new version only after the current latest has been released for some amount of time. 

I like to try to avoid problem versions by waiting for the version number not to change for a bit but, so far, it's been a pretty manual process as of now.

**Comment by mag37** [comment]
Sadly this is not an easy thing to implement as I'm not comparing version numbers anywhere and version tags don't really follow a specific standard.

All I do with this script it check if there's an image with a different checksum (at the same tag if set, else latest) than the one currently running locally. And if so its considered newer.

It's a good suggestion and something I looked into briefly, but I couldnt find a failsafe way of implementing it.

**Comment by mag37** [comment]
> Can you not check the age of the new image? All that I really care about is that the new image is X days old. I wouldn't want to change tags or anything.

I've not had time to fully check this out yet, but I've got a proof of concept that seems to work to grab the dates of the latest build of each image (including tag I think, need to test this further).

Seems possible to build - though it would also mean 2 checks per image on the repo instead of just one.

I'll dive deeper when I've got time to spare but for now - this is my testing:
`regctl image inspect "b4bz/homer" --format='{{.Created}}' `

**Comment by adamshand** [comment]
Just wanted to say this is something I've been wishing for as well. Thanks for looking into it!

**Comment by mag37** [comment]
I've just pushed a branch I've been working on, try it if you want to:
https://github.com/mag37/dockcheck/tree/agecheck

I'll merge with main as soon as I've done some more  testing.
