### ISSUE TITLE
Raspberry Pi - Cannot install regctl

### ISSUE THREAD

**Issue by halphalp** [mag37/dockcheck#52]
hi! i recently tried cloning the dockcheck repo to my raspberry pi (running raspberry pi os bookworm) to update docker containers, but received an error when installing dependencies that my architecture is not supported for regctl.

has anyone found a way to run dockcheck on their raspberry pi with this being considered?

**Comment by mag37** [comment]
This is due to the binaries from [regclient](https://github.com/regclient/regclient/blob/main/docs/install.md) are *amd64* or *arm64* architecture (rpi3, rpi4, rpiZ2). So if you've got an older Pi (or 32bit OS for other reasons) there's no binaries that supports it.

What you could do is a work-around - where you run regctl in a contianer and wrap it in a shell script. It's not the most elegant solution and it'll be slower than having the proper binary. But it works.

Copied from [regclient/docs/install.md](https://github.com/regclient/regclient/blob/main/docs/install.md):

```sh
cat >regctl <<EOF
#!/bin/sh
opts=""
case "\$*" in
  "registry login"*) opts="-t";;
esac
docker container run \$opts -i --rm --net host \\
  -u "\$(id -u):\$(id -g)" -e HOME -v \$HOME:\$HOME \\
  -v /etc/docker/certs.d:/etc/docker/certs.d:ro \\
  ghcr.io/regclient/regctl:latest "\$@"
EOF
chmod 755 regctl
```

Test it with `./regctl --help` and then either add the file to the same path as *dockcheck.sh* or in your path (eg. `~/.local/bin/regctl`).

I might add this to the readme actually, have forgotten to do any work around supporting older architecture.

**Comment by yoyoma2** [comment]
I have an old rpi2 on which I recently installed docker so I just tried dockcheck and it failed. The workaround given above worked for me thanks! Amazing what docker can do!

**Comment by mag37** [comment]
Yeah I'm glad it worked - I tested it on a rpi2 myself just to be sure before suggesting :)

Added this to the readme going up in the next version.
