### ISSUE TITLE
[FEATURE REQUEST] Automatically download latest in use notification add-on

### ISSUE THREAD

**Issue by yoyoma2** [mag37/dockcheck#64]
Add a comment tag in each notification add-on template giving its filename and a "do not delete" warning.

If a notify.sh file exists, grep for that tag and automatically also download that template file when automatically downloading dockcheck.sh.

The user's changes are safe in notify.sh but it's now easy to diff notify.sh notify_xxx.sh to see if the new dockcheck version has also improved the template being used.

**Comment by mag37** [comment]
The idea is good, but I don't know how useful it will be - the templates are there as a basic template for the user to keep building and modifying after their own needs. The template itself will most likely not change much after the initial release.

If a template have to change in the future it would be because the "general" usage in the example no longer works. And then the user will most likely realize issues with their notify before I can patch a fix anyway.

I'll consider it still though! Wont close it.

**Comment by yoyoma2** [comment]
You are probably right. I did it manually once today and there were indeed no changes. Also even though I have docker and dockcheck on several machines, I only use notify.sh on a single machine so notification template updates aren't a big thing. Does github have a secure way to exchange emails? I would bounce ideas off of you offline instead of on github. Closing...

**Comment by mag37** [comment]
I've been trying to find a way to send private messages before on Github but think there's none.

You're more then welcome to bounce the ideas though, maybe through discussions instead of issues?
