### ISSUE TITLE
Running with -a -y still ends with interaction (pruning images)

### ISSUE THREAD

**Issue by zilexa** [mag37/dockcheck#91]
`dockcheck -a -y` after updating ends with: 
```
All done!
Would you like to prune dangling images? y/[n]: 
```
I expect that to happen automatically since I used -y. Not sure if that's even possible?

**Comment by mag37** [comment]
It was deliberate due to the `-p` option that will auto-prune, but I realize it's not that intuitive when you choose a "auto" option. To auto-prune right now you'll do `dockcheck -yp`.

Though when thinking about it, running with `-a|-y` option should probably skip the prune-interaction and default to "no" prune - I'll consider this change!

(And btw. The `-a` and `-y` flag is the same option (if you look at the readme/help) so running both wont make any difference.)

**Comment by zilexa** [comment]
Oh I thought -a was automatic and -y was unattended/no interaction. 
My actual goal is to make your tool output, part of a monthly maintenance script, for my home server. 
The script performs a few basic actions (cleaning up, updating the system, updating docker, btrfs filesystem maintenance, remaining space per media folder calculation) and relevant output is added to a textfile, which becomes the body of an email.

Just the "Containers on latest version" and "Containers with updates available" is the output from your tool I want to add to the textfile. Not the actual updating, that would lead to a long and messy email.

So I would run your script twice. Once `dockcheck -n` > output to textfile and then a second run `dockcheck -ap` to update and prune automatically :)

**Comment by mag37** [comment]
Been a couple of days - have you tried my suggestion @zilexa ? 

May I consider this resolved and close it? 

I'll probably change the code to skip the prune-interaction (default 'no') when running with `-a|-y` without `-p`

**Comment by zilexa** [comment]
yes feel free to close, I have been caught up by work unfortunately. But I will definitely test and use it in the suggested way. A change as you suggest would be a welcome one!
