### ISSUE TITLE
Send notification after updating container

### ISSUE THREAD

**Issue by Joop9** [mag37/dockcheck#95]
Currently, I've only receive a (mail)notification when there is an update available. 
Can I also receive a notification when the container is updated? 

Current situation when updates available:
I've a notification after running  `dockcheck.sh -i -n -s`
But I don't get a notification after updating some containers with `dockcheck.sh -i -p -s -a -d 14 ` (only there are updates available, same message as above). 

Best regards,
Joop9

**Comment by mag37** [comment]
The notification -option got added because people expressed the need to get notified with available updates and then manually trigger the updating themselves. Hence I didn't consider creating it "before and after".

I also think people who run a command similar to your 2nd example `dockcheck.sh -ipsa` just use the list they got sent as a way of knowing which containers have been updated.

Though I see your point, that it'd be nice to get a list of successful, confirmed updates. It's a whole other logic to be added for that to function though I'm afraid.

**Comment by mag37** [comment]
I'll consider this stale and will close as "not planned" if no objections.

While not exactly what you ask for, one way of achieving this is to run it in reverse order.
- First:  `dockcheck.sh -i -p -s -a -d 14` - then you'll get notified of updates avaiable and also trigger the update itself.
- Second:  `dockcheck.sh -i -n -s` - which will notify you if there's any containers that still need updates (rest will be "cleared" from the list after successful updates).
